version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: main
    labels:
    - dependabot
  - package-ecosystem: "gradle"
    directory: "/"
    commit-message:
      prefix: BAU
    schedule:
      interval: "weekly"
    target-branch: main
    labels:
    - dependabot
