name: Package for Dev
on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set up JDK
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.11.2

      - name: Setup SAM
        uses: aws-actions/setup-sam@f84ec7d548307efafe33230528756de3c5841a17 # v2
        with:
          version: 1.159.1 # 2026-05-20 resolving https://github.com/aws/aws-sam-cli/issues/9027

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3
        with:
          gradle-version: "9.6.1"
      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2.2.0
        with:
          role-to-assume: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t infrastructure/lambda/template.yaml

      - name: SAM build
        run: |
          mkdir out
          sam build -t ./infrastructure/lambda/template.yaml -b ./out/

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@720ddb75fba8951db5a648ebb416eb233f1b6bc9 # v3.10.1
        with:
          artifact-bucket-name: ${{ secrets.DEV_ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.DEV_SIGNING_PROFILE_NAME }}
          working-directory: ./out
